### ISSUE TITLE
Invalid credentials error

### ISSUE THREAD

**Issue by brianmituka** [sendyit/prestashop#1]
I'm trying out your module but I keep getting the invalid credentials error and I don't know the exact issue

**Comment by thegeektets** [comment]
hey @brianmituka the module is still under development, you are welcome to test but will definitely let you know when it is ready.

**Comment by brianmituka** [comment]
@thegeektets is the module ready yet? I tried the latest version but it seems like the google maps api has issues. I get this error in the console after adding the module to prestashop: Failed to load resource: ``` the server responded with a status of 403 ()
index.php:1 Refused to execute script from 'https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate?1shttp%3A%2F%2Flocalhost%2Ftest%2Findex.php&4sAIzaSyB-qgooVsnsVKnyF8zc30DscS1z5jZ9K-4&callback=_xdc_._idiobc&token=104933' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.```

**Comment by thegeektets** [comment]
@brianmituka we will have a look at this and get back to you ...

**Comment by thegeektets** [comment]
@brianmituka we updated the module please have a look test and let me know if you are still having challenges

**Comment by brianmituka** [comment]
I've tested it and it works fine. Thanks

**Comment by thegeektets** [comment]
I am closing this issue, please reopen or open a new issue if you have any challenges
